#!/usr/bin/env python3
"""
Augment extracted case-study JSON files with AI-assisted fields.

Input:  JSON files from pipeline/extracted (one object per file), generated by extract_from_html.py.
Output: For each English file, an augmented JSON alongside the original:
        page_0.json -> page_0_en_augmented.json

Augmentations:
- Geocoding: infer coordinates from geographic_characterisation (with cache).
- Implementation years: extract start/end years from fulltext (with cache).
- Text preprocessing for selected fields: 'references' and 'contact' (with cache).
- Recipe: structured sections from fulltext (with cache); output under recipe.lang / recipe.ingredients.

Notes:
- Uses Google Gemini via google-genai SDK.
- All AI calls are cached under pipeline/caches/ to avoid recomputation.
"""

import argparse
import hashlib
import json
import os
import sys
import time
from pathlib import Path

import geocoder
from dotenv import load_dotenv
from google import genai
from google.genai import types


REPO_ROOT = Path(__file__).resolve().parent.parent
PIPELINE_DIR = REPO_ROOT / "pipeline"
CACHE_DIR = PIPELINE_DIR / "caches"
DEFAULT_OUTPUT_DIR = PIPELINE_DIR / "augmented"

# Ensure cache directory exists
CACHE_DIR.mkdir(parents=True, exist_ok=True)

# Load environment variables from .env file (repo or pipeline root)
load_dotenv(REPO_ROOT / ".env")
load_dotenv(PIPELINE_DIR / ".env")

# API keys / model configuration
ARCGIS_API_KEY = os.getenv("ARCGIS_API_KEY", "")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# Define model globally so it is easy to update.
# google-genai expects model IDs like "gemini-2.0-flash", not "gemini/...".
_raw_model = os.getenv("GEMINI_MODEL", "gemini-3-flash-preview")
GEMINI_MODEL = _raw_model.split("/")[-1]

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not set. Please define it in .env.", file=sys.stderr)
    sys.exit(1)

genai_client = genai.Client(api_key=GEMINI_API_KEY)

# Cache files (under pipeline/caches/)
GEOCODE_CACHE_FILE = CACHE_DIR / "geocode_cache.json"
YEARS_CACHE_FILE = CACHE_DIR / "years_cache.json"
PREPROCESS_CACHE_FILE = CACHE_DIR / "preprocess_cache.json"
SUMMARY_CACHE_FILE = CACHE_DIR / "summary_cache.json"
COST_ESTIMATION_CACHE_FILE = CACHE_DIR / "cost_estimation_cache.json"
RECIPE_EXTRACTION_CACHE_FILE = CACHE_DIR / "recipe_extraction_cache.json"

# Bump when the recipe prompt or canonical ingredients shape changes (invalidates cache file entries).
RECIPE_EXTRACTION_CACHE_VERSION = "v1"


def _load_json_cache(path: Path) -> dict:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception as e:  # noqa: BLE001
            print(f"Error loading cache {path.name}: {e}", file=sys.stderr)
            return {}
    return {}


def _save_json_cache(path: Path, cache: dict) -> None:
    try:
        path.write_text(json.dumps(cache, indent=2, ensure_ascii=False), encoding="utf-8")
    except Exception as e:  # noqa: BLE001
        print(f"Error saving cache {path.name}: {e}", file=sys.stderr)


global_geocode_cache = _load_json_cache(GEOCODE_CACHE_FILE)
global_years_cache = _load_json_cache(YEARS_CACHE_FILE)
global_preprocess_cache = _load_json_cache(PREPROCESS_CACHE_FILE)
global_summary_cache = _load_json_cache(SUMMARY_CACHE_FILE)
global_cost_estimation_cache = _load_json_cache(COST_ESTIMATION_CACHE_FILE)
global_recipe_extraction_cache = _load_json_cache(RECIPE_EXTRACTION_CACHE_FILE)

# Canonical keys stored in DB / augmented JSON (order stable for dumps).
RECIPE_CANONICAL_KEYS: tuple[str, ...] = (
    "who_is_involved",
    "economic_data",
    "context_summary",
    "challenges",
    "policy_context",
    "legal_aspects",
    "objectives",
    "solutions_implemented",
    "implementation_phases",
    "success_and_limiting",
    "benefits",
    "lessons_learnt",
    "transferability",
)

# Map JSON keys from the model to canonical ingredient keys.
RECIPE_MODEL_TO_CANONICAL: dict[str, str] = {
    "who_is_involved": "who_is_involved",
    "economic_data": "economic_data",
    "context_summary": "context_summary",
    "context_challenges": "challenges",
    "context_policy": "policy_context",
    "context_legal_aspects": "legal_aspects",
    "objectives": "objectives",
    "solutions_implemented": "solutions_implemented",
    "implementation_phases": "implementation_phases",
    "success_and_limiting_factors": "success_and_limiting",
    "benefits": "benefits",
    "lessons_learnt": "lessons_learnt",
    "transferability": "transferability",
}


def _normalize_geo_value(value: str | None) -> str:
    """Return first segment if comma-separated, trimmed; empty string if missing."""
    if not value or not isinstance(value, str):
        return ""
    return value.split(",")[0].strip()


def _build_geocode_queries(geo: dict) -> list[str]:
    """
    Build an ordered list of geocode query strings from geographic_characterisation.
    Order: most specific (city) to least specific (continent). Empty queries are omitted.
    """
    city = _normalize_geo_value(geo.get("city"))
    sub_national = _normalize_geo_value(geo.get("sub_nationals"))
    country = _normalize_geo_value(geo.get("countries"))
    macro_region = _normalize_geo_value(geo.get("macro_transnational_region"))
    continent = _normalize_geo_value(geo.get("continent"))

    queries = []
    seen = set()

    def add(q: str) -> None:
        if q and q not in seen:
            seen.add(q)
            queries.append(q)

    # 1. City + country (best precision)
    if city and country:
        add(f"{city}, {country}")
    # 2. City + sub_national + country (e.g. "Kerry County, Southern and Eastern, Ireland")
    if city and sub_national and country:
        add(f"{city}, {sub_national}, {country}")
    # 3. City alone
    if city:
        add(city)
    # 4. Sub nationals + country (first segment to keep query focused)
    if sub_national and country:
        add(f"{sub_national}, {country}")
    # 5. Sub nationals alone (often includes region name)
    if sub_national:
        add(sub_national)
    # 6. Country alone
    if country:
        add(country)
    # 7. Macro-transnational region (e.g. Atlantic Area)
    if macro_region:
        add(macro_region)
    # 8. Continent (last resort, coarse)
    if continent:
        add(continent)

    return queries


def get_coordinates(location_info: dict) -> tuple[float | None, float | None]:
    """
    Get coordinates for a location using geocoding, with caching.
    Expects geographic_characterisation dict with optional keys: city, sub_nationals,
    countries, macro_transnational_region, continent. Tries queries from most specific
    (city + country) to least specific (continent) and returns the first successful result.
    Returns (lat, lon) or (None, None) if nothing found.
    """
    location_queries = _build_geocode_queries(location_info)
    if not location_queries:
        print("No geographic data available for geocoding.")
        return None, None

    print(f"\nGeocoding (most specific → least): {location_queries}")
    global global_geocode_cache

    for query in location_queries:
        if not query or not query.strip():
            continue

        # Cache lookup
        if query in global_geocode_cache:
            latlon = global_geocode_cache[query]
            print(f"Found coordinates in cache for '{query}': {latlon}")
            return latlon[0], latlon[1]

        print(f"Trying query: {query}")
        try:
            # ArcGIS first
            if ARCGIS_API_KEY:
                try:
                    g = geocoder.arcgis(query, key=ARCGIS_API_KEY)
                    if g.ok:
                        print(f"Found coordinates using ArcGIS: {g.latlng}")
                        global_geocode_cache[query] = g.latlng
                        _save_json_cache(GEOCODE_CACHE_FILE, global_geocode_cache)
                        return g.latlng[0], g.latlng[1]
                except Exception as e:  # noqa: BLE001
                    print(f"Error with ArcGIS service: {e}", file=sys.stderr)

            # Fallback to Google if available
            if GOOGLE_API_KEY:
                try:
                    g = geocoder.google(query, key=GOOGLE_API_KEY)
                    if g.ok:
                        print(f"Found coordinates using Google: {g.latlng}")
                        global_geocode_cache[query] = g.latlng
                        _save_json_cache(GEOCODE_CACHE_FILE, global_geocode_cache)
                        return g.latlng[0], g.latlng[1]
                except Exception as e:  # noqa: BLE001
                    print(f"Error with Google service: {e}", file=sys.stderr)

            print(f"No results found for query: {query}")
            time.sleep(1)
        except Exception as e:  # noqa: BLE001
            print(f"Geocoding error for {query}: {e}", file=sys.stderr)
            time.sleep(2)
            continue

    print("No coordinates found for any query")
    return None, None


def extract_years_from_fulltext(fulltext: str) -> dict | str:
    """
    Use Gemini to extract starting and ending years from the case-study fulltext.
    Returns a JSON-like dict {'start_year': 'YYYY', 'end_year': 'YYYY'} or
    an empty string if not possible. Uses a cache keyed by the fulltext.
    """
    global global_years_cache
    if not fulltext:
        return ""

    # To avoid extremely long prompts, truncate very long texts
    text = fulltext.strip()
    if len(text) > 8000:
        text = text[:8000]

    if text in global_years_cache:
        cached = global_years_cache[text]
        # If we previously cached an empty string (e.g. from an error),
        # treat it as a miss so we can retry with a now-correct setup.
        if cached != "":
            print("Found years in cache for given fulltext.")
            return cached

    try:
        prompt = (
            "This text describes an adaptation case study, which may include information "
            "about when the adaptation project or measure was implemented.\n\n"
            "Task:\n"
            "- Carefully scan the text and extract the starting and ending years of the implementation period.\n"
            "- If you can only find one year, return it as 'start_year' and leave 'end_year' empty.\n"
            "- If the text does not contain any clear information about implementation years, return an empty string.\n\n"
            "Return format:\n"
            '- Either an empty string ""\n'
            "- Or a JSON object like: {\"start_year\": \"2015\", \"end_year\": \"2020\"}\n\n"
            "Text:\n"
            f"{text}"
        )
        print("Calling Gemini API for implementation years extraction...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(max_output_tokens=150),
        )

        result_text: str | None = None
        if hasattr(response, "text") and response.text:
            result_text = response.text
        elif hasattr(response, "candidates") and response.candidates:
            candidate = response.candidates[0]
            if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
                if isinstance(candidate.content.parts, list):
                    result_text = "".join(
                        [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                    )
                else:
                    result_text = str(candidate.content.parts)
            elif hasattr(candidate.content, "text"):
                result_text = candidate.content.text

        print("Extracted result_text for years:", result_text)
        if not result_text:
            global_years_cache[text] = ""
            _save_json_cache(YEARS_CACHE_FILE, global_years_cache)
            return ""

        cleaned_text = (
            result_text.strip()
            .replace("```json", "")
            .replace("```", "")
            .strip()
        )
        try:
            result = json.loads(cleaned_text)
            # Normalise to expected shape
            if not isinstance(result, dict):
                raise ValueError("Years result is not a dict")
            start_year = str(result.get("start_year", "") or "")
            end_year = str(result.get("end_year", "") or "")
            out = {"start_year": start_year, "end_year": end_year}
            global_years_cache[text] = out
            _save_json_cache(YEARS_CACHE_FILE, global_years_cache)
            return out
        except Exception:  # noqa: BLE001
            print("Years response is not valid JSON:", cleaned_text, file=sys.stderr)
            global_years_cache[text] = ""
            _save_json_cache(YEARS_CACHE_FILE, global_years_cache)
            return ""
    except Exception as e:  # noqa: BLE001
        print(f"Error extracting years from fulltext: {e}", file=sys.stderr)
        global_years_cache[text] = ""
        _save_json_cache(YEARS_CACHE_FILE, global_years_cache)
        return ""


def summarize_fulltext(fulltext: str) -> str:
    """
    Generate a short textual summary (one or two paragraphs) of the case-study fulltext.
    Uses a cache keyed by the (possibly truncated) fulltext plus a prompt version.
    """
    global global_summary_cache
    if not fulltext:
        return ""

    text = fulltext.strip()
    # Avoid overlong prompts; keep enough context for a good summary
    if len(text) > 12000:
        text = text[:12000]

    cache_version = "v1"
    cache_key = f"{cache_version}:{text}"
    if cache_key in global_summary_cache:
        return global_summary_cache[cache_key]

    try:
        prompt = (
            "You are summarizing a climate change adaptation case study.\n\n"
            "Task:\n"
            "- Read the text below (markdown-style fulltext of the case study).\n"
            "- Write a concise summary of the case study in ONE or TWO paragraphs.\n"
            "- Focus on: context/problem, main adaptation measures, key actors, and main outcomes/benefits.\n"
            "- Keep it neutral, factual, and suitable for a database description.\n"
            "- Length target: roughly 150–250 words.\n"
            "- Do NOT add headings, bullet points, or metadata labels; return only plain text paragraphs.\n\n"
            "Case study text:\n"
            f"{text}"
        )
        print("Calling Gemini API for fulltext summary...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(max_output_tokens=400),
        )

        result_text: str | None = None
        if hasattr(response, "text") and response.text:
            result_text = response.text
        elif hasattr(response, "candidates") and response.candidates:
            candidate = response.candidates[0]
            if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
                if isinstance(candidate.content.parts, list):
                    result_text = "".join(
                        [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                    )
                else:
                    result_text = str(candidate.content.parts)
            elif hasattr(candidate.content, "text"):
                result_text = candidate.content.text

        summary = (result_text or "").strip()
        global_summary_cache[cache_key] = summary
        _save_json_cache(SUMMARY_CACHE_FILE, global_summary_cache)
        return summary
    except Exception as e:  # noqa: BLE001
        print(f"Error summarizing fulltext: {e}", file=sys.stderr)
        global_summary_cache[cache_key] = ""
        _save_json_cache(SUMMARY_CACHE_FILE, global_summary_cache)
        return ""


def extract_cost_estimation(cost_benefit_text: str | None) -> float | None:
    """
    Use Gemini to extract a numeric cost estimation (EUR) from the cost_benefit text.
    Returns a float or None if no clear cost is found. Cached with versioned key.
    """
    global global_cost_estimation_cache
    if not cost_benefit_text or not isinstance(cost_benefit_text, str):
        return None

    text = cost_benefit_text.strip()
    if not text:
        return None

    if len(text) > 8000:
        text = text[:8000]

    cache_version = "v1"
    cache_key = f"{cache_version}:{text}"
    if cache_key in global_cost_estimation_cache:
        cached = global_cost_estimation_cache[cache_key]
        print("Found cost estimation in cache.")
        return cached

    try:
        prompt = (
            "You are analysing the costs and benefits section of a climate-change adaptation case study.\n\n"
            "Task:\n"
            "- Read the text below and extract the total or most representative project cost in EUR.\n"
            "- Return ONLY a JSON object in one of these two forms:\n"
            '  {\"cost_estimation\": 14000}   (a number, no currency symbol)\n'
            '  {\"cost_estimation\": null}     (if no clear numeric cost is present)\n'
            "- If the text mentions multiple amounts, pick the one that best represents the overall project cost.\n"
            "- If only unit costs are mentioned (e.g. €20 per meter) without a total, return null.\n"
            "- Do NOT invent or calculate numbers that are not explicitly stated.\n\n"
            "Text:\n"
            f"{text}"
        )
        print("Calling Gemini API for cost estimation extraction...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(max_output_tokens=100),
        )

        result_text: str | None = None
        if hasattr(response, "text") and response.text:
            result_text = response.text
        elif hasattr(response, "candidates") and response.candidates:
            candidate = response.candidates[0]
            if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
                if isinstance(candidate.content.parts, list):
                    result_text = "".join(
                        [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                    )
                else:
                    result_text = str(candidate.content.parts)
            elif hasattr(candidate.content, "text"):
                result_text = candidate.content.text

        print("Extracted result_text for cost estimation:", result_text)
        if not result_text:
            global_cost_estimation_cache[cache_key] = None
            _save_json_cache(COST_ESTIMATION_CACHE_FILE, global_cost_estimation_cache)
            return None

        cleaned_text = (
            result_text.strip()
            .replace("```json", "")
            .replace("```", "")
            .strip()
        )
        try:
            result = json.loads(cleaned_text)
            if not isinstance(result, dict):
                raise ValueError("Cost estimation result is not a dict")
            raw_value = result.get("cost_estimation")
            if raw_value is None:
                global_cost_estimation_cache[cache_key] = None
                _save_json_cache(COST_ESTIMATION_CACHE_FILE, global_cost_estimation_cache)
                return None
            cost = float(raw_value)
            global_cost_estimation_cache[cache_key] = cost
            _save_json_cache(COST_ESTIMATION_CACHE_FILE, global_cost_estimation_cache)
            return cost
        except Exception:  # noqa: BLE001
            print("Cost estimation response is not valid JSON:", cleaned_text, file=sys.stderr)
            global_cost_estimation_cache[cache_key] = None
            _save_json_cache(COST_ESTIMATION_CACHE_FILE, global_cost_estimation_cache)
            return None
    except Exception as e:  # noqa: BLE001
        print(f"Error extracting cost estimation: {e}", file=sys.stderr)
        global_cost_estimation_cache[cache_key] = None
        _save_json_cache(COST_ESTIMATION_CACHE_FILE, global_cost_estimation_cache)
        return None


def empty_recipe_ingredients() -> dict[str, str]:
    """All canonical keys as empty strings (no LLM / DB write ambiguity)."""
    return {k: "" for k in RECIPE_CANONICAL_KEYS}


def _coerce_recipe_section_value(val) -> str:  # noqa: ANN001
    if val is None:
        return ""
    if isinstance(val, str):
        return val.strip()
    if isinstance(val, (dict, list)):
        return json.dumps(val, ensure_ascii=False)
    return str(val).strip()


def normalize_recipe_ingredients(raw: dict) -> dict[str, str]:
    """Map model JSON keys to canonical keys; drop title, short_description, sdgs, and unknown keys."""
    out = empty_recipe_ingredients()
    if not isinstance(raw, dict):
        return out
    for model_key, canon in RECIPE_MODEL_TO_CANONICAL.items():
        if model_key not in raw:
            continue
        out[canon] = _coerce_recipe_section_value(raw.get(model_key))
    return out


_RECIPE_PROMPT_TEMPLATE = """You are a specialist in summarizing climate adaptation case studies.
You will receive the raw text of a case study. Your task is to extract
and rewrite the content into standardized sections and return them as a
single JSON object.

CRITICAL RULES:
- Only use information explicitly present in the source text.
- If a section has no corresponding content in the source, return an
  empty string "" for that key.
- Do not infer, estimate, or expand beyond what is stated.
- Do not merge content between sections.
- Return only the JSON object. No preamble, no explanation, no markdown
  code blocks.
- Do NOT include keys for title, short_description, or SDGs.

**Formatting instructions:**
The json object values must be formatted in markdown.
- Each key should have only text as the single value, no arrays or any other complex data types.
- Use **bold** for important concepts, numbers, and names.
- Do not use arrays for list of items, use bullet points or numbered lists instead.
- Use bullet points or numbered lists where appropriate.
- Add extra line breaks between sections for clarity.
- Make the markdown visually attractive and easy to scan.

Voice  type:
 - Professional
 - concise
 - factual
 - kind


The JSON object must have exactly these keys:

{
  "who_is_involved":
    Identify the main organizations, institutions, or groups that
    participated. For each, briefly state their role or responsibility.
    Mention any participatory processes (surveys, consultations,
    workshops) and their effect on the project. Write as flowing prose,
    2-4 sentences. Do not include individual names or contact details.,

  "economic_data":
    All financial and cost-related information: total project cost and
    what it covered, whether tools are free or paid, any variable costs.
    Include references to other resources for cost details if mentioned.
    Factual only — do not estimate or infer costs not explicitly stated.,

  "context_summary":
    3-5 sentences capturing the essence: what problem it addresses, what
    solution was developed, where it was implemented, and who led it.
    Standalone introduction for someone unfamiliar with the case.,

  "context_challenges":
    The specific environmental, technical, or operational problems that
    motivated the project. Include climate-related risks, knowledge gaps,
    or urgency factors mentioned. Do not add challenges not explicitly
    stated.,

  "context_policy":
    The policy framework within which the project was developed. Include
    specific plans, programmes, or government strategies explicitly named
    in the source. Only include what is explicitly mentioned.,

  "context_legal_aspects":
    Laws, regulations, directives, or legal obligations mentioned.
    Include article or paragraph references if provided. Do not interpret
    or infer legal implications beyond what is stated.,

  "objectives":
    The stated goals of the project as a numbered list. Keep original
    intent but rephrase for clarity. Do not add objectives not explicitly
    mentioned.,

  "solutions_implemented":
    Concrete actions, tools, systems, or measures put in place. Preserve
    any numbered structure from the source. Include specific outputs and
    quantitative details only if explicitly stated.,

  "implementation_phases":
    Dates, durations, milestones, or sequencing information in
    chronological order. Only what is explicitly stated in the source.,

  "success_and_limiting_factors":
    Two clearly labelled subsections: (1) success factors and (2)
    limiting factors. Only include factors explicitly discussed — do not
    generalise or add assumed factors.,

  "benefits":
    Environmental, social, economic, or institutional benefits mentioned.
    Reflect whether benefits are confirmed or expected/unquantified. Do not
    attribute numbers or outcomes not explicitly stated.,

  "lessons_learnt":
    Key takeaways explicitly stated by the project authors. May relate to
    process, stakeholder engagement, tool design, or knowledge transfer. Do not derive lessons from other sections.,

  "transferability":
    What the source says about replicating or adapting this approach
    elsewhere. Include conditions, required adaptations, or existing
    replications mentioned. Only what is explicitly stated.
}

Case study text:
"""


def _gemini_result_text(response) -> str | None:  # noqa: ANN001
    result_text: str | None = None
    if hasattr(response, "text") and response.text:
        result_text = response.text
    elif hasattr(response, "candidates") and response.candidates:
        candidate = response.candidates[0]
        if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
            if isinstance(candidate.content.parts, list):
                result_text = "".join(
                    [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                )
            else:
                result_text = str(candidate.content.parts)
        elif hasattr(candidate.content, "text"):
            result_text = candidate.content.text
    return result_text


def extract_recipe(source_text: str) -> dict[str, str]:
    """
    Extract recipe sections from case-study body text (uses `fulltext` in practice).
    Cached under pipeline/caches/recipe_extraction_cache.json (versioned SHA256 key).
    """
    global global_recipe_extraction_cache
    if not source_text or not isinstance(source_text, str):
        return empty_recipe_ingredients()

    text = source_text.strip()
    if not text:
        return empty_recipe_ingredients()

    if len(text) > 48000:
        text = text[:48000]

    cache_key = f"{RECIPE_EXTRACTION_CACHE_VERSION}:{hashlib.sha256(text.encode('utf-8')).hexdigest()}"
    if cache_key in global_recipe_extraction_cache:
        cached = global_recipe_extraction_cache[cache_key]
        if isinstance(cached, dict):
            print("Found recipe extraction in cache.")
            merged = empty_recipe_ingredients()
            for k in RECIPE_CANONICAL_KEYS:
                v = cached.get(k)
                merged[k] = v if isinstance(v, str) else ""
            return merged

    prompt = _RECIPE_PROMPT_TEMPLATE + text

    def call_and_parse() -> dict[str, str] | None:
        print("Calling Gemini API for recipe extraction...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(max_output_tokens=8192),
        )
        result_text = _gemini_result_text(response)
        if not result_text:
            return None
        cleaned = (
            result_text.strip()
            .replace("```json", "")
            .replace("```", "")
            .strip()
        )
        try:
            parsed = json.loads(cleaned)
        except json.JSONDecodeError:
            print("Recipe extraction response is not valid JSON:", cleaned[:500], file=sys.stderr)
            return None
        if not isinstance(parsed, dict):
            print("Recipe extraction JSON is not an object.", file=sys.stderr)
            return None
        return normalize_recipe_ingredients(parsed)

    try:
        normalized = call_and_parse()
        if normalized is None:
            normalized = call_and_parse()
        if normalized is None:
            normalized = empty_recipe_ingredients()
        global_recipe_extraction_cache[cache_key] = normalized
        _save_json_cache(RECIPE_EXTRACTION_CACHE_FILE, global_recipe_extraction_cache)
        return normalized
    except Exception as e:  # noqa: BLE001
        print(f"Error extracting recipe: {e}", file=sys.stderr)
        fallback = empty_recipe_ingredients()
        global_recipe_extraction_cache[cache_key] = fallback
        _save_json_cache(RECIPE_EXTRACTION_CACHE_FILE, global_recipe_extraction_cache)
        return fallback


def preprocess_text_field(field_value, field_type: str):  # noqa: ANN001
    """
    Preprocess a text field (e.g. references or contact) using Gemini and cache the result.
    The cache key is based on field_type + field_value.
    """
    global global_preprocess_cache
    if not field_value:
        return field_value

    # If we got a list (e.g. references as list of dicts), stringify it in a readable way.
    if isinstance(field_value, list):
        parts = []
        for entry in field_value:
            if isinstance(entry, dict):
                title = entry.get("title") or ""
                url = entry.get("url") or ""
                combined = f"{title} ({url})".strip()
                if combined:
                    parts.append(combined)
            else:
                parts.append(str(entry))
        field_value = "\n".join(f"- {p}" for p in parts if p)

    # Versioned cache key so we can evolve prompts without being stuck with stale entries.
    cache_version = "v2"
    cache_key = f"{cache_version}:{field_type}:{field_value}"
    if cache_key in global_preprocess_cache:
        return global_preprocess_cache[cache_key]

    try:
        if field_type == "contact":
            prompt = (
                "Format the following contact information from a climate adaptation case study "
                "as clear multi-line markdown:\n"
                "- Use one bullet per person (start each person with '- ').\n"
                "- On the first line, show 'Name, role' if available.\n"
                "- On the next line, show 'Email: <address>' (ensure exactly one space after 'Email:').\n"
                "- On following line(s), show 'Website: <URL>' or other URLs as needed.\n"
                "- Preserve email addresses and URLs exactly as given.\n"
                "- Do NOT add commentary, explanations, or introductory/closing sentences.\n"
                "- Output ONLY the cleaned contact content.\n\n"
                "Contact field content:\n"
                f"{field_value}"
            )
        else:
            prompt = (
                f"Clean and structure the following {field_type} field from a climate adaptation case study.\n"
                "- Return a well-formatted, human-readable version.\n"
                "- Split multiple entries into a clear list if appropriate.\n"
                "- Keep emails, phone numbers, and URLs explicit and easy to see.\n"
                "- Do NOT add commentary, explanations, or introductory/closing sentences.\n"
                "- Output ONLY the cleaned content.\n\n"
                "Field content:\n"
                f"{field_value}"
            )
        print(f"Calling Gemini API to preprocess field '{field_type}'...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(max_output_tokens=600),
        )

        result_text: str | None = None
        if hasattr(response, "text") and response.text:
            result_text = response.text
        elif hasattr(response, "candidates") and response.candidates:
            candidate = response.candidates[0]
            if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
                if isinstance(candidate.content.parts, list):
                    result_text = "".join(
                        [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                    )
                else:
                    result_text = str(candidate.content.parts)
            elif hasattr(candidate.content, "text"):
                result_text = candidate.content.text

        if not result_text:
            print(f"ERROR: Gemini API did not return any text for {field_type}!", file=sys.stderr)
            global_preprocess_cache[cache_key] = field_value
            _save_json_cache(PREPROCESS_CACHE_FILE, global_preprocess_cache)
            return field_value

        cleaned = result_text.strip()
        global_preprocess_cache[cache_key] = cleaned
        _save_json_cache(PREPROCESS_CACHE_FILE, global_preprocess_cache)
        return cleaned
    except Exception as e:  # noqa: BLE001
        print(f"Error preprocessing {field_type}: {e}", file=sys.stderr)
        global_preprocess_cache[cache_key] = field_value
        _save_json_cache(PREPROCESS_CACHE_FILE, global_preprocess_cache)
        return field_value


def augment_record(data: dict) -> dict:
    """
    Apply all augmentations to a single extracted record.
    - Geocoding from geographic_characterisation -> location.lat/lon
    - Years from fulltext -> implementation_years
    - Preprocess references/contact -> references_preprocessed/contact_preprocessed
    - Cost estimation from cost_benefit -> cost_estimation
    - Recipe sections from fulltext -> recipe.lang + recipe.ingredients
    """
    # Geocoding
    geo_info = data.get("geographic_characterisation")
    if isinstance(geo_info, dict):
        lat, lon = get_coordinates(geo_info)
        if lat is not None and lon is not None:
            data["location"] = {"lat": lat, "lon": lon}

    # Years (prefer implementation_time section if present, otherwise fall back to fulltext)
    fulltext = data.get("fulltext", "") or ""
    years_source_text = (data.get("implementation_time") or fulltext).strip()
    years_info = extract_years_from_fulltext(years_source_text)
    if years_info:
        # Preserve the existing field name from previous pipeline
        data["implementation_years"] = years_info

    # Preprocess selected text fields (we keep originals and add *_preprocessed)
    for field in ("references", "contact"):
        if field in data and data[field]:
            key_out = f"{field}_preprocessed"
            data[key_out] = preprocess_text_field(data[field], field)

    # Summary of fulltext (one or two paragraphs)
    if fulltext:
        summary = summarize_fulltext(fulltext)
        if summary:
            data["summary"] = summary

    # Cost estimation from cost_benefit text
    cost_benefit_text = data.get("cost_benefit")
    data["cost_estimation"] = extract_cost_estimation(cost_benefit_text)

    # Recipe (standardized sections; title/summary live in summary_multilang when pushed)
    data["recipe"] = {
        "lang": "en",
        "ingredients": extract_recipe(fulltext),
    }

    return data


def process_file(path: Path, output_dir: Path) -> None:
    """
    Read one extracted JSON file, augment it (for English records),
    and write page_X_en_augmented.json alongside.
    """
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:  # noqa: BLE001
        print(f"Error reading {path}: {e}", file=sys.stderr)
        return

    if not isinstance(raw, dict):
        print(f"Skipping {path.name}: expected a single JSON object.", file=sys.stderr)
        return

    lang = raw.get("lang", "en")
    if lang != "en":
        print(f"Skipping {path.name}: lang={lang} (only processing English).")
        return

    print(f"\nAugmenting {path.name} (lang=en)...")
    augmented = augment_record(dict(raw))  # work on a copy

    out_name = f"{path.stem}_en_augmented.json"
    out_path = output_dir / out_name
    out_path.write_text(json.dumps(augmented, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote augmented file: {out_path.relative_to(REPO_ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Augment extracted case-study JSON files with AI-derived fields (geocoding, years, preprocessing)."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=PIPELINE_DIR / "extracted",
        help="Directory containing extracted JSON files (default: pipeline/extracted).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where augmented JSON files will be written (default: pipeline/augmented).",
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="page_*.json",
        help="Glob pattern to select input JSON files (default: page_*.json).",
    )
    args = parser.parse_args()

    if not args.input.exists():
        print(f"Input directory does not exist: {args.input}", file=sys.stderr)
        return 1

    args.output.mkdir(parents=True, exist_ok=True)

    files = sorted(args.input.glob(args.pattern))
    # Skip already-augmented files to avoid infinite *_en_augmented_en_augmented... chains
    files = [p for p in files if not p.name.endswith("_en_augmented.json")]
    if not files:
        print(f"No JSON files matched {args.pattern} in {args.input}", file=sys.stderr)
        return 1

    print(f"Found {len(files)} JSON files to augment in {args.input}")
    for path in files:
        process_file(path, args.output)

    print("Augmentation complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

