#!/usr/bin/env python3
"""
Augment extracted case-study JSON files with AI-assisted fields.

Input:  JSON files from pipeline/extracted (one object per file), generated by extract_from_html.py.
Output: For each English file, an augmented JSON alongside the original:
        page_0.json -> page_0_en_augmented.json

Augmentations:
- Geocoding: infer coordinates from geographic_characterisation (with cache).
- Implementation years: extract start/end years from fulltext (with cache).
- Text preprocessing for selected fields: 'references' and 'contact' (with cache).
- Recipe: structured sections from fulltext (with cache); output under recipe.lang / recipe.ingredients.

Notes:
- Uses Google Gemini via google-genai SDK.
- All AI calls are cached under pipeline/caches/ to avoid recomputation.
"""

import argparse
import hashlib
import json
import os
import re
import sys
import time
from pathlib import Path

import geocoder
from dotenv import load_dotenv
from google import genai
from google.genai import types


REPO_ROOT = Path(__file__).resolve().parent.parent
PIPELINE_DIR = REPO_ROOT / "pipeline"
CACHE_DIR = PIPELINE_DIR / "caches"
DEFAULT_OUTPUT_DIR = PIPELINE_DIR / "augmented"

# Ensure cache directory exists
CACHE_DIR.mkdir(parents=True, exist_ok=True)

# Load environment variables from .env file (repo or pipeline root)
load_dotenv(REPO_ROOT / ".env")
load_dotenv(PIPELINE_DIR / ".env")

# API keys / model configuration
ARCGIS_API_KEY = os.getenv("ARCGIS_API_KEY", "")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# Define model globally so it is easy to update.
# google-genai expects model IDs like "gemini-2.0-flash", not "gemini/...".
_raw_model = os.getenv("GEMINI_MODEL", "gemini-3.1-flash-lite")
GEMINI_MODEL = _raw_model.split("/")[-1]

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not set. Please define it in .env.", file=sys.stderr)
    sys.exit(1)

genai_client = genai.Client(api_key=GEMINI_API_KEY)

# Cache files (under pipeline/caches/)
GEOCODE_CACHE_FILE = CACHE_DIR / "geocode_cache.json"
YEARS_CACHE_FILE = CACHE_DIR / "years_cache.json"
PREPROCESS_CACHE_FILE = CACHE_DIR / "preprocess_cache.json"
SUMMARY_CACHE_FILE = CACHE_DIR / "summary_cache.json"
COST_ESTIMATION_CACHE_FILE = CACHE_DIR / "cost_estimation_cache.json"
RECIPE_EXTRACTION_CACHE_FILE = CACHE_DIR / "recipe_extraction_cache.json"

# Bump when the recipe prompt or canonical ingredients shape changes (invalidates cache file entries).
RECIPE_EXTRACTION_CACHE_VERSION = "v2"

# Bump when years prompt / JSON contract changes (invalidates years_cache.json keys).
YEARS_CACHE_KEY_PREFIX = "v2:"


def _load_json_cache(path: Path) -> dict:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception as e:  # noqa: BLE001
            print(f"Error loading cache {path.name}: {e}", file=sys.stderr)
            return {}
    return {}


def _save_json_cache(path: Path, cache: dict) -> None:
    try:
        path.write_text(json.dumps(cache, indent=2, ensure_ascii=False), encoding="utf-8")
    except Exception as e:  # noqa: BLE001
        print(f"Error saving cache {path.name}: {e}", file=sys.stderr)


global_geocode_cache = _load_json_cache(GEOCODE_CACHE_FILE)
global_years_cache = _load_json_cache(YEARS_CACHE_FILE)
global_preprocess_cache = _load_json_cache(PREPROCESS_CACHE_FILE)
global_summary_cache = _load_json_cache(SUMMARY_CACHE_FILE)
global_cost_estimation_cache = _load_json_cache(COST_ESTIMATION_CACHE_FILE)
global_recipe_extraction_cache = _load_json_cache(RECIPE_EXTRACTION_CACHE_FILE)

# Canonical keys stored in DB / augmented JSON (order stable for dumps).
RECIPE_CANONICAL_KEYS: tuple[str, ...] = (
    "who_is_involved",
    "economic_data",
    "context_summary",
    "challenges",
    "policy_context",
    "legal_aspects",
    "objectives",
    "solutions_implemented",
    "implementation_phases",
    "success_and_limiting",
    "benefits",
    "lessons_learnt",
    "transferability",
)

# Map JSON keys from the model to canonical ingredient keys.
# Includes legacy `context_*` names from older prompts; structured JSON uses canonical names.
RECIPE_MODEL_TO_CANONICAL: dict[str, str] = {
    "who_is_involved": "who_is_involved",
    "economic_data": "economic_data",
    "context_summary": "context_summary",
    "context_challenges": "challenges",
    "challenges": "challenges",
    "context_policy": "policy_context",
    "policy_context": "policy_context",
    "context_legal_aspects": "legal_aspects",
    "legal_aspects": "legal_aspects",
    "objectives": "objectives",
    "solutions_implemented": "solutions_implemented",
    "implementation_phases": "implementation_phases",
    "success_and_limiting_factors": "success_and_limiting",
    "success_and_limiting": "success_and_limiting",
    "benefits": "benefits",
    "lessons_learnt": "lessons_learnt",
    "transferability": "transferability",
}


def _normalize_geo_value(value: str | None) -> str:
    """Return first segment if comma-separated, trimmed; empty string if missing."""
    if not value or not isinstance(value, str):
        return ""
    return value.split(",")[0].strip()


def _build_geocode_queries(geo: dict) -> list[str]:
    """
    Build an ordered list of geocode query strings from geographic_characterisation.
    Order: most specific (city) to least specific (continent). Empty queries are omitted.
    """
    city = _normalize_geo_value(geo.get("city"))
    sub_national = _normalize_geo_value(geo.get("sub_nationals"))
    country = _normalize_geo_value(geo.get("countries"))
    macro_region = _normalize_geo_value(geo.get("macro_transnational_region"))
    continent = _normalize_geo_value(geo.get("continent"))

    queries = []
    seen = set()

    def add(q: str) -> None:
        if q and q not in seen:
            seen.add(q)
            queries.append(q)

    # 1. City + country (best precision)
    if city and country:
        add(f"{city}, {country}")
    # 2. City + sub_national + country (e.g. "Kerry County, Southern and Eastern, Ireland")
    if city and sub_national and country:
        add(f"{city}, {sub_national}, {country}")
    # 3. City alone
    if city:
        add(city)
    # 4. Sub nationals + country (first segment to keep query focused)
    if sub_national and country:
        add(f"{sub_national}, {country}")
    # 5. Sub nationals alone (often includes region name)
    if sub_national:
        add(sub_national)
    # 6. Country alone
    if country:
        add(country)
    # 7. Macro-transnational region (e.g. Atlantic Area)
    if macro_region:
        add(macro_region)
    # 8. Continent (last resort, coarse)
    if continent:
        add(continent)

    return queries


def get_coordinates(location_info: dict) -> tuple[float | None, float | None]:
    """
    Get coordinates for a location using geocoding, with caching.
    Expects geographic_characterisation dict with optional keys: city, sub_nationals,
    countries, macro_transnational_region, continent. Tries queries from most specific
    (city + country) to least specific (continent) and returns the first successful result.
    Returns (lat, lon) or (None, None) if nothing found.
    """
    location_queries = _build_geocode_queries(location_info)
    if not location_queries:
        print("No geographic data available for geocoding.")
        return None, None

    print(f"\nGeocoding (most specific → least): {location_queries}")
    global global_geocode_cache

    for query in location_queries:
        if not query or not query.strip():
            continue

        # Cache lookup
        if query in global_geocode_cache:
            latlon = global_geocode_cache[query]
            print(f"Found coordinates in cache for '{query}': {latlon}")
            return latlon[0], latlon[1]

        print(f"Trying query: {query}")
        try:
            # ArcGIS first
            if ARCGIS_API_KEY:
                try:
                    g = geocoder.arcgis(query, key=ARCGIS_API_KEY)
                    if g.ok:
                        print(f"Found coordinates using ArcGIS: {g.latlng}")
                        global_geocode_cache[query] = g.latlng
                        _save_json_cache(GEOCODE_CACHE_FILE, global_geocode_cache)
                        return g.latlng[0], g.latlng[1]
                except Exception as e:  # noqa: BLE001
                    print(f"Error with ArcGIS service: {e}", file=sys.stderr)

            # Fallback to Google if available
            if GOOGLE_API_KEY:
                try:
                    g = geocoder.google(query, key=GOOGLE_API_KEY)
                    if g.ok:
                        print(f"Found coordinates using Google: {g.latlng}")
                        global_geocode_cache[query] = g.latlng
                        _save_json_cache(GEOCODE_CACHE_FILE, global_geocode_cache)
                        return g.latlng[0], g.latlng[1]
                except Exception as e:  # noqa: BLE001
                    print(f"Error with Google service: {e}", file=sys.stderr)

            print(f"No results found for query: {query}")
            time.sleep(1)
        except Exception as e:  # noqa: BLE001
            print(f"Geocoding error for {query}: {e}", file=sys.stderr)
            time.sleep(2)
            continue

    print("No coordinates found for any query")
    return None, None


def extract_years_from_fulltext(fulltext: str) -> dict | str:
    """
    Use Gemini to extract starting and ending years from the case-study fulltext.
    Returns a JSON-like dict {'start_year': 'YYYY', 'end_year': 'YYYY'} or
    an empty string if not possible. Uses a cache keyed by the fulltext.
    """
    global global_years_cache
    if not fulltext:
        return ""

    # To avoid extremely long prompts, truncate very long texts
    text = fulltext.strip()
    if len(text) > 8000:
        text = text[:8000]

    years_cache_key = YEARS_CACHE_KEY_PREFIX + text
    if years_cache_key in global_years_cache:
        cached = global_years_cache[years_cache_key]
        print("Found years in cache for given fulltext.")
        return cached

    # Backfill from the pre-v2 cache shape when it has a useful value.
    legacy_cached = global_years_cache.get(text)
    if legacy_cached not in (None, ""):
        print("Found years in legacy cache for given fulltext.")
        global_years_cache[years_cache_key] = legacy_cached
        _save_json_cache(YEARS_CACHE_FILE, global_years_cache)
        return legacy_cached

    def fallback_years_from_text() -> dict | str:
        """Cheap fallback for transient/partial Gemini JSON failures."""
        years = [int(y) for y in re.findall(r"\b(?:19|20)\d{2}\b", text)]
        if not years:
            return ""
        start_year = str(min(years))
        end_year = str(max(years))
        if start_year == end_year:
            end_year = ""
        out = {"start_year": start_year, "end_year": end_year}
        print(f"  [YEARS] fallback regex -> {out}")
        return out

    years_schema = types.Schema(
        type=types.Type.OBJECT,
        properties={
            "start_year": types.Schema(
                type=types.Type.STRING,
                description="First year of implementation (YYYY) or empty if unknown",
            ),
            "end_year": types.Schema(
                type=types.Type.STRING,
                description="Last year of implementation (YYYY) or empty if unknown or ongoing",
            ),
        },
        required=["start_year", "end_year"],
    )

    try:
        prompt = (
            "This text describes an adaptation case study, which may include information "
            "about when the adaptation project or measure was implemented.\n\n"
            "Task:\n"
            "- Extract the starting and ending calendar years of the main implementation or project period.\n"
            "- Prefer four-digit years (e.g. 2015) when the source gives them.\n"
            "- If only one year is stated, return it in start_year and set end_year to an empty string.\n"
            "- If no implementation years are present in the text, set both fields to empty strings.\n"
            "Respond with JSON only (the schema is enforced by the API).\n\n"
            "Text:\n"
            f"{text}"
        )
        print("Calling Gemini API for implementation years extraction...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                max_output_tokens=2048,
                temperature=0,
                response_mime_type="application/json",
                response_schema=years_schema,
                thinking_config=types.ThinkingConfig(include_thoughts=False),
            ),
        )

        result = _parse_json_object_from_gemini(response)
        if not result:
            if response is not None and _gemini_result_text(response) is not None:
                print(
                    "Years response could not be parsed as JSON object:",
                    (_gemini_result_text(response) or "")[:300],
                    file=sys.stderr,
                )
            else:
                print("Years response was empty (no text).", file=sys.stderr)
            _log_gemini_response_debug("years", response)
            fallback = fallback_years_from_text()
            global_years_cache[years_cache_key] = fallback
            _save_json_cache(YEARS_CACHE_FILE, global_years_cache)
            return fallback

        start_year = str(result.get("start_year", "") or "")
        end_year = str(result.get("end_year", "") or "")
        out = {"start_year": start_year, "end_year": end_year}
        global_years_cache[years_cache_key] = out
        _save_json_cache(YEARS_CACHE_FILE, global_years_cache)
        return out
    except Exception as e:  # noqa: BLE001
        print(f"Error extracting years from fulltext: {e}", file=sys.stderr)
        global_years_cache[years_cache_key] = ""
        _save_json_cache(YEARS_CACHE_FILE, global_years_cache)
        return ""


def summarize_fulltext(fulltext: str) -> str:
    """
    Generate a short textual summary (one or two paragraphs) of the case-study fulltext.
    Uses a cache keyed by the (possibly truncated) fulltext plus a prompt version.
    """
    global global_summary_cache
    if not fulltext:
        return ""

    text = fulltext.strip()
    # Avoid overlong prompts; keep enough context for a good summary
    if len(text) > 12000:
        text = text[:12000]

    cache_version = "v1"
    cache_key = f"{cache_version}:{text}"
    if cache_key in global_summary_cache:
        return global_summary_cache[cache_key]

    try:
        prompt = (
            "You are summarizing a climate change adaptation case study.\n\n"
            "Task:\n"
            "- Read the text below (markdown-style fulltext of the case study).\n"
            "- Write a concise summary of the case study in ONE or TWO paragraphs.\n"
            "- Focus on: context/problem, main adaptation measures, key actors, and main outcomes/benefits.\n"
            "- Keep it neutral, factual, and suitable for a database description.\n"
            "- Length target: roughly 150–250 words.\n"
            "- Do NOT add headings, bullet points, or metadata labels; return only plain text paragraphs.\n\n"
            "Case study text:\n"
            f"{text}"
        )
        print("Calling Gemini API for fulltext summary...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(max_output_tokens=400),
        )

        result_text: str | None = None
        if hasattr(response, "text") and response.text:
            result_text = response.text
        elif hasattr(response, "candidates") and response.candidates:
            candidate = response.candidates[0]
            if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
                if isinstance(candidate.content.parts, list):
                    result_text = "".join(
                        [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                    )
                else:
                    result_text = str(candidate.content.parts)
            elif hasattr(candidate.content, "text"):
                result_text = candidate.content.text

        summary = (result_text or "").strip()
        global_summary_cache[cache_key] = summary
        _save_json_cache(SUMMARY_CACHE_FILE, global_summary_cache)
        return summary
    except Exception as e:  # noqa: BLE001
        print(f"Error summarizing fulltext: {e}", file=sys.stderr)
        global_summary_cache[cache_key] = ""
        _save_json_cache(SUMMARY_CACHE_FILE, global_summary_cache)
        return ""


def extract_cost_estimation(cost_benefit_text: str | None) -> float | None:
    """
    Use Gemini to extract a numeric cost estimation (EUR) from the cost_benefit text.
    Returns a float or None if no clear cost is found. Cached with versioned key.
    """
    global global_cost_estimation_cache
    if not cost_benefit_text or not isinstance(cost_benefit_text, str):
        return None

    text = cost_benefit_text.strip()
    if not text:
        return None

    if len(text) > 8000:
        text = text[:8000]

    cache_version = "v1"
    cache_key = f"{cache_version}:{text}"
    if cache_key in global_cost_estimation_cache:
        cached = global_cost_estimation_cache[cache_key]
        print("Found cost estimation in cache.")
        return cached

    try:
        prompt = (
            "You are analysing the costs and benefits section of a climate-change adaptation case study.\n\n"
            "Task:\n"
            "- Read the text below and extract the total or most representative project cost in EUR.\n"
            "- Return ONLY a JSON object in one of these two forms:\n"
            '  {\"cost_estimation\": 14000}   (a number, no currency symbol)\n'
            '  {\"cost_estimation\": null}     (if no clear numeric cost is present)\n'
            "- If the text mentions multiple amounts, pick the one that best represents the overall project cost.\n"
            "- If only unit costs are mentioned (e.g. €20 per meter) without a total, return null.\n"
            "- Do NOT invent or calculate numbers that are not explicitly stated.\n\n"
            "Text:\n"
            f"{text}"
        )
        print("Calling Gemini API for cost estimation extraction...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(max_output_tokens=100),
        )

        result_text: str | None = None
        if hasattr(response, "text") and response.text:
            result_text = response.text
        elif hasattr(response, "candidates") and response.candidates:
            candidate = response.candidates[0]
            if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
                if isinstance(candidate.content.parts, list):
                    result_text = "".join(
                        [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                    )
                else:
                    result_text = str(candidate.content.parts)
            elif hasattr(candidate.content, "text"):
                result_text = candidate.content.text

        print("Extracted result_text for cost estimation:", result_text)
        if not result_text:
            global_cost_estimation_cache[cache_key] = None
            _save_json_cache(COST_ESTIMATION_CACHE_FILE, global_cost_estimation_cache)
            return None

        cleaned_text = (
            result_text.strip()
            .replace("```json", "")
            .replace("```", "")
            .strip()
        )
        try:
            result = json.loads(cleaned_text)
            if not isinstance(result, dict):
                raise ValueError("Cost estimation result is not a dict")
            raw_value = result.get("cost_estimation")
            if raw_value is None:
                global_cost_estimation_cache[cache_key] = None
                _save_json_cache(COST_ESTIMATION_CACHE_FILE, global_cost_estimation_cache)
                return None
            cost = float(raw_value)
            global_cost_estimation_cache[cache_key] = cost
            _save_json_cache(COST_ESTIMATION_CACHE_FILE, global_cost_estimation_cache)
            return cost
        except Exception:  # noqa: BLE001
            print("Cost estimation response is not valid JSON:", cleaned_text, file=sys.stderr)
            global_cost_estimation_cache[cache_key] = None
            _save_json_cache(COST_ESTIMATION_CACHE_FILE, global_cost_estimation_cache)
            return None
    except Exception as e:  # noqa: BLE001
        print(f"Error extracting cost estimation: {e}", file=sys.stderr)
        global_cost_estimation_cache[cache_key] = None
        _save_json_cache(COST_ESTIMATION_CACHE_FILE, global_cost_estimation_cache)
        return None


def empty_recipe_ingredients() -> dict[str, str]:
    """All canonical keys as empty strings (no LLM / DB write ambiguity)."""
    return {k: "" for k in RECIPE_CANONICAL_KEYS}


def _coerce_recipe_section_value(val) -> str:  # noqa: ANN001
    if val is None:
        return ""
    if isinstance(val, str):
        return val.strip()
    if isinstance(val, (dict, list)):
        return json.dumps(val, ensure_ascii=False)
    return str(val).strip()


def normalize_recipe_ingredients(raw: dict) -> dict[str, str]:
    """Map model JSON keys to canonical keys; drop title, short_description, sdgs, and unknown keys.

    The prompt asks for `context_challenges` etc., but some models return canonical names
    (`challenges`, …) instead — those are merged in a second pass when a slot is still empty.
    """
    out = empty_recipe_ingredients()
    if not isinstance(raw, dict):
        return out
    for model_key, canon in RECIPE_MODEL_TO_CANONICAL.items():
        if model_key not in raw:
            continue
        out[canon] = _coerce_recipe_section_value(raw.get(model_key))
    for k in RECIPE_CANONICAL_KEYS:
        if k in raw and not (out.get(k) or "").strip():
            v = _coerce_recipe_section_value(raw.get(k))
            if v:
                out[k] = v
    return out


def has_renderable_recipe_ingredients(ingredients: dict[str, str]) -> bool:
    """Same basic rule as the UI: at least one section has non-blank text."""
    return any(isinstance(v, str) and v.strip() for v in ingredients.values())


_RECIPE_PROMPT_TEMPLATE = """You are a specialist in summarizing climate adaptation case studies.
You will receive the raw text of a case study. The API will ask you for a JSON object
with a fixed set of string fields. Each value is one markdown string; use an empty
string for any section with no content in the source.

CRITICAL RULES:
- Only use information explicitly present in the source text.
- If a section has no corresponding content in the source, use an empty string for that key.
- Do not infer, estimate, or expand beyond what is stated.
- Do not merge content between distinct sections.
- Do NOT add title, short_description, or SDG fields (not part of the schema).

Formatting inside each string value (markdown):
- Use **bold** for important concepts, numbers, and names.
- Use bullet or numbered lists (not JSON arrays) for list-like content in the string.
- Add line breaks for readability. Voice: professional, concise, factual, kind.

Section guide (one JSON string field per item; use the exact key names the schema provides):

- who_is_involved: Organizations, institutions, or groups; roles; participatory processes (2–4 sentences; no private contact details).
- economic_data: Financial or cost information as stated; no invented figures.
- context_summary: 3–5 sentence standalone overview (problem, solution, place, lead actors).
- challenges: Environmental, technical, or operational problems; climate risks; only from the source.
- policy_context: Named plans, strategies, or programmes; only as stated.
- legal_aspects: Laws, regulations, or obligations; only as stated.
- objectives: Project goals; numbered list in markdown if the source is structured.
- solutions_implemented: Concrete measures, systems, or outputs; preserve numbering if present.
- implementation_phases: Time sequence (dates, durations, milestones); only as stated.
- success_and_limiting: Two subsections: success factors and limiting factors; only factors discussed in the source.
- benefits: Environmental, social, economic, or institutional benefits; no invented outcomes.
- lessons_learnt: Stated takeaways only; do not import from other sections.
- transferability: Replication, conditions, or upscaling; only as stated.

Case study text:
"""


def _gemini_result_text(response) -> str | None:  # noqa: ANN001
    result_text: str | None = None
    if hasattr(response, "text") and response.text:
        result_text = response.text
    elif hasattr(response, "candidates") and response.candidates:
        candidate = response.candidates[0]
        if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
            if isinstance(candidate.content.parts, list):
                result_text = "".join(
                    [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                )
            else:
                result_text = str(candidate.content.parts)
        elif hasattr(candidate.content, "text"):
            result_text = candidate.content.text
    return result_text


def _log_gemini_response_debug(label: str, response) -> None:  # noqa: ANN001
    """Print compact Gemini response diagnostics when structured parsing fails."""
    if response is None:
        print(f"[Gemini:{label}] no response object", file=sys.stderr)
        return
    usage = getattr(response, "usage_metadata", None)
    if usage is not None and hasattr(usage, "model_dump"):
        print(f"[Gemini:{label}] usage={usage.model_dump()}", file=sys.stderr)
    candidates = getattr(response, "candidates", None) or []
    if not candidates:
        print(f"[Gemini:{label}] no candidates", file=sys.stderr)
        return
    candidate = candidates[0]
    finish_reason = getattr(candidate, "finish_reason", None)
    finish_message = getattr(candidate, "finish_message", None)
    token_count = getattr(candidate, "token_count", None)
    safety = getattr(candidate, "safety_ratings", None)
    print(
        f"[Gemini:{label}] finish_reason={finish_reason} "
        f"finish_message={finish_message!r} token_count={token_count}",
        file=sys.stderr,
    )
    if safety:
        print(f"[Gemini:{label}] safety_ratings={safety}", file=sys.stderr)


def _parse_json_object_from_gemini(response) -> dict | None:  # noqa: ANN001
    """
    Structured JSON (response_mime_type + response_schema) sets `response.parsed`.
    Otherwise parse `response.text` as JSON. Returns a dict or None.
    """
    if response is None:
        return None
    parsed = getattr(response, "parsed", None)
    if parsed is not None:
        if isinstance(parsed, dict):
            return parsed
        if hasattr(parsed, "model_dump") and callable(parsed.model_dump):
            dumped = parsed.model_dump()
            return dumped if isinstance(dumped, dict) else None
    result_text = _gemini_result_text(response)
    if not result_text or not str(result_text).strip():
        return None
    cleaned = (
        str(result_text)
        .strip()
        .replace("```json", "")
        .replace("```", "")
        .strip()
    )
    if not cleaned:
        return None
    try:
        out = json.loads(cleaned)
    except json.JSONDecodeError:
        return None
    return out if isinstance(out, dict) else None


def _recipe_ingredients_json_schema() -> types.Schema:
    """JSON schema for knowledge.recipe.ingredients (canonical string keys, markdown values)."""
    props: dict[str, types.Schema] = {}
    for key in RECIPE_CANONICAL_KEYS:
        label = " ".join(key.split("_"))
        props[key] = types.Schema(
            type=types.Type.STRING,
            description=f"Markdown for {label} section, or empty if not in the source.",
        )
    return types.Schema(
        type=types.Type.OBJECT,
        properties=props,
    )


def extract_recipe(source_text: str) -> dict[str, str]:
    """
    Extract recipe sections from case-study body text (uses `fulltext` in practice).
    Cached under pipeline/caches/recipe_extraction_cache.json (versioned SHA256 key).
    """
    global global_recipe_extraction_cache
    if not source_text or not isinstance(source_text, str):
        return empty_recipe_ingredients()

    text = source_text.strip()
    if not text:
        return empty_recipe_ingredients()

    if len(text) > 48000:
        text = text[:48000]

    text_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()
    cache_key = f"{RECIPE_EXTRACTION_CACHE_VERSION}:{text_hash}"
    if cache_key in global_recipe_extraction_cache:
        cached = global_recipe_extraction_cache[cache_key]
        if isinstance(cached, dict):
            print("Found recipe extraction in cache.")
            return normalize_recipe_ingredients(cached)

    # Reuse good v1 recipe cache entries instead of recomputing every article after the v2 bump.
    legacy_cache_key = f"v1:{text_hash}"
    cached = global_recipe_extraction_cache.get(legacy_cache_key)
    if isinstance(cached, dict):
        normalized_cached = normalize_recipe_ingredients(cached)
        if has_renderable_recipe_ingredients(normalized_cached):
            print("Found recipe extraction in legacy cache.")
            global_recipe_extraction_cache[cache_key] = normalized_cached
            _save_json_cache(RECIPE_EXTRACTION_CACHE_FILE, global_recipe_extraction_cache)
            return normalized_cached

    prompt = _RECIPE_PROMPT_TEMPLATE + text

    def call_and_parse() -> dict[str, str] | None:
        print("Calling Gemini API for recipe extraction...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                max_output_tokens=8192,
                temperature=0,
                response_mime_type="application/json",
                response_schema=_recipe_ingredients_json_schema(),
                thinking_config=types.ThinkingConfig(include_thoughts=False),
            ),
        )
        parsed = _parse_json_object_from_gemini(response)
        if not parsed:
            snippet = (_gemini_result_text(response) or "")[:500]
            print("Recipe extraction could not obtain JSON object:", snippet, file=sys.stderr)
            _log_gemini_response_debug("recipe", response)
            return None
        return normalize_recipe_ingredients(parsed)

    try:
        normalized = call_and_parse()
        if normalized is None:
            normalized = call_and_parse()
        if normalized is None:
            print("Recipe extraction failed after retries; not caching empty fallback.", file=sys.stderr)
            return empty_recipe_ingredients()
        if has_renderable_recipe_ingredients(normalized):
            global_recipe_extraction_cache[cache_key] = normalized
        else:
            print("Recipe extraction returned all-empty ingredients; not caching.", file=sys.stderr)
        _save_json_cache(RECIPE_EXTRACTION_CACHE_FILE, global_recipe_extraction_cache)
        return normalized
    except Exception as e:  # noqa: BLE001
        print(f"Error extracting recipe: {e}", file=sys.stderr)
        return empty_recipe_ingredients()


def preprocess_text_field(field_value, field_type: str):  # noqa: ANN001
    """
    Preprocess a text field (e.g. references or contact) using Gemini and cache the result.
    The cache key is based on field_type + field_value.
    """
    global global_preprocess_cache
    if not field_value:
        return field_value

    # If we got a list (e.g. references as list of dicts), stringify it in a readable way.
    if isinstance(field_value, list):
        parts = []
        for entry in field_value:
            if isinstance(entry, dict):
                title = entry.get("title") or ""
                url = entry.get("url") or ""
                combined = f"{title} ({url})".strip()
                if combined:
                    parts.append(combined)
            else:
                parts.append(str(entry))
        field_value = "\n".join(f"- {p}" for p in parts if p)

    # Versioned cache key so we can evolve prompts without being stuck with stale entries.
    cache_version = "v2"
    cache_key = f"{cache_version}:{field_type}:{field_value}"
    if cache_key in global_preprocess_cache:
        return global_preprocess_cache[cache_key]

    try:
        if field_type == "contact":
            prompt = (
                "Format the following contact information from a climate adaptation case study "
                "as clear multi-line markdown:\n"
                "- Use one bullet per person (start each person with '- ').\n"
                "- On the first line, show 'Name, role' if available.\n"
                "- On the next line, show 'Email: <address>' (ensure exactly one space after 'Email:').\n"
                "- On following line(s), show 'Website: <URL>' or other URLs as needed.\n"
                "- Preserve email addresses and URLs exactly as given.\n"
                "- Do NOT add commentary, explanations, or introductory/closing sentences.\n"
                "- Output ONLY the cleaned contact content.\n\n"
                "Contact field content:\n"
                f"{field_value}"
            )
        else:
            prompt = (
                f"Clean and structure the following {field_type} field from a climate adaptation case study.\n"
                "- Return a well-formatted, human-readable version.\n"
                "- Split multiple entries into a clear list if appropriate.\n"
                "- Keep emails, phone numbers, and URLs explicit and easy to see.\n"
                "- Do NOT add commentary, explanations, or introductory/closing sentences.\n"
                "- Output ONLY the cleaned content.\n\n"
                "Field content:\n"
                f"{field_value}"
            )
        print(f"Calling Gemini API to preprocess field '{field_type}'...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(max_output_tokens=600),
        )

        result_text: str | None = None
        if hasattr(response, "text") and response.text:
            result_text = response.text
        elif hasattr(response, "candidates") and response.candidates:
            candidate = response.candidates[0]
            if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
                if isinstance(candidate.content.parts, list):
                    result_text = "".join(
                        [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                    )
                else:
                    result_text = str(candidate.content.parts)
            elif hasattr(candidate.content, "text"):
                result_text = candidate.content.text

        if not result_text:
            print(f"ERROR: Gemini API did not return any text for {field_type}!", file=sys.stderr)
            global_preprocess_cache[cache_key] = field_value
            _save_json_cache(PREPROCESS_CACHE_FILE, global_preprocess_cache)
            return field_value

        cleaned = result_text.strip()
        global_preprocess_cache[cache_key] = cleaned
        _save_json_cache(PREPROCESS_CACHE_FILE, global_preprocess_cache)
        return cleaned
    except Exception as e:  # noqa: BLE001
        print(f"Error preprocessing {field_type}: {e}", file=sys.stderr)
        global_preprocess_cache[cache_key] = field_value
        _save_json_cache(PREPROCESS_CACHE_FILE, global_preprocess_cache)
        return field_value


def augment_record(data: dict) -> dict:
    """
    Apply all augmentations to a single extracted record.
    - Geocoding from geographic_characterisation -> location.lat/lon
    - Years from fulltext -> implementation_years
    - Preprocess references/contact -> references_preprocessed/contact_preprocessed
    - Cost estimation from cost_benefit -> cost_estimation
    - Recipe sections from fulltext -> recipe.lang + recipe.ingredients
    """
    # Geocoding
    geo_info = data.get("geographic_characterisation")
    if isinstance(geo_info, dict):
        lat, lon = get_coordinates(geo_info)
        if lat is not None and lon is not None:
            data["location"] = {"lat": lat, "lon": lon}

    # Years (prefer implementation_time section if present, otherwise fall back to fulltext)
    fulltext = data.get("fulltext", "") or ""
    years_source_text = (data.get("implementation_time") or fulltext).strip()
    years_info = extract_years_from_fulltext(years_source_text)
    if years_info:
        # Preserve the existing field name from previous pipeline
        data["implementation_years"] = years_info

    # Preprocess selected text fields (we keep originals and add *_preprocessed)
    for field in ("references", "contact"):
        if field in data and data[field]:
            key_out = f"{field}_preprocessed"
            data[key_out] = preprocess_text_field(data[field], field)

    # Summary of fulltext (one or two paragraphs)
    if fulltext:
        summary = summarize_fulltext(fulltext)
        if summary:
            data["summary"] = summary

    # Cost estimation from cost_benefit text
    cost_benefit_text = data.get("cost_benefit")
    data["cost_estimation"] = extract_cost_estimation(cost_benefit_text)

    # Recipe (standardized sections; title/summary live in summary_multilang when pushed)
    data["recipe"] = {
        "lang": "en",
        "ingredients": extract_recipe(fulltext),
    }

    return data


def process_file(path: Path, output_dir: Path) -> None:
    """
    Read one extracted JSON file, augment it (for English records),
    and write page_X_en_augmented.json alongside.
    """
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:  # noqa: BLE001
        print(f"Error reading {path}: {e}", file=sys.stderr)
        return

    if not isinstance(raw, dict):
        print(f"Skipping {path.name}: expected a single JSON object.", file=sys.stderr)
        return

    lang = raw.get("lang", "en")
    if lang != "en":
        print(f"Skipping {path.name}: lang={lang} (only processing English).")
        return

    print(f"\nAugmenting {path.name} (lang=en)...")
    augmented = augment_record(dict(raw))  # work on a copy

    out_name = f"{path.stem}_en_augmented.json"
    out_path = output_dir / out_name
    out_path.write_text(json.dumps(augmented, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote augmented file: {out_path.relative_to(REPO_ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Augment extracted case-study JSON files with AI-derived fields (geocoding, years, preprocessing)."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=PIPELINE_DIR / "extracted",
        help="Directory containing extracted JSON files (default: pipeline/extracted).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where augmented JSON files will be written (default: pipeline/augmented).",
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="page_*.json",
        help="Glob pattern to select input JSON files (default: page_*.json).",
    )
    args = parser.parse_args()

    if not args.input.exists():
        print(f"Input directory does not exist: {args.input}", file=sys.stderr)
        return 1

    args.output.mkdir(parents=True, exist_ok=True)

    files = sorted(args.input.glob(args.pattern))
    # Skip already-augmented files to avoid infinite *_en_augmented_en_augmented... chains
    files = [p for p in files if not p.name.endswith("_en_augmented.json")]
    if not files:
        print(f"No JSON files matched {args.pattern} in {args.input}", file=sys.stderr)
        return 1

    print(f"Found {len(files)} JSON files to augment in {args.input}")
    for path in files:
        process_file(path, args.output)

    print("Augmentation complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

