#!/usr/bin/env python3
"""
Translate user-visible fields from augmented case-study JSON files into another language.

Input:  JSON files from pipeline/augmented (one object per file), generated by augment_with_ai.py.
Output: For each input file, a translation-only JSON:
        page_0_en_augmented.json -> page_0_en_augmented_es.json

Translated fields:
- fulltext
- title
- summary
- subtitle

Each translation JSON contains:
- source_file: original HTML file path (foreign key)
- lang: target language code (e.g. "es")
- title, subtitle, summary, fulltext: translated strings
"""

import argparse
import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from google.genai import types


REPO_ROOT = Path(__file__).resolve().parent.parent
PIPELINE_DIR = REPO_ROOT / "pipeline"
DEFAULT_INPUT_DIR = PIPELINE_DIR / "augmented"

# Load env from repo and pipeline
load_dotenv(REPO_ROOT / ".env")
load_dotenv(PIPELINE_DIR / ".env")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not set. Please define it in .env.", file=sys.stderr)
    sys.exit(1)

# Normalise model ID for google-genai (strip provider prefix like 'gemini/')
_raw_model = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
GEMINI_MODEL = _raw_model.split("/")[-1]

genai_client = genai.Client(api_key=GEMINI_API_KEY)

# Translation cache
CACHE_DIR = PIPELINE_DIR / "caches"
CACHE_DIR.mkdir(parents=True, exist_ok=True)
TRANSLATION_CACHE_FILE = CACHE_DIR / "translation_cache.json"


def _load_json_cache(path: Path) -> dict:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception as e:  # noqa: BLE001
            print(f"Error loading cache {path.name}: {e}", file=sys.stderr)
            return {}
    return {}


def _save_json_cache(path: Path, cache: dict) -> None:
    try:
        path.write_text(json.dumps(cache, indent=2, ensure_ascii=False), encoding="utf-8")
    except Exception as e:  # noqa: BLE001
        print(f"Error saving cache {path.name}: {e}", file=sys.stderr)


global_translation_cache = _load_json_cache(TRANSLATION_CACHE_FILE)


def _translate_text(text: str, target_lang: str, field: str) -> str:
    """
    Translate a single text field to target_lang, with caching.

    field is one of: fulltext, title, summary, subtitle.
    """
    global global_translation_cache
    if not text:
        return ""

    # To keep prompts reasonable, truncate very long texts (mostly relevant for fulltext).
    src = text.strip()
    if len(src) > 20000:
        src = src[:20000]

    cache_version = "v1"
    cache_key = f"{cache_version}:{target_lang}:{field}:{src}"
    if cache_key in global_translation_cache:
        return global_translation_cache[cache_key]

    # Field-specific instructions
    if field == "fulltext":
        extra = (
            "- Preserve the markdown structure (headings, bullet lists, code blocks) as much as possible.\n"
            "- Preserve links and URLs; translate only the descriptive text.\n"
        )
        length_hint = "- Keep roughly the same length and level of detail as the original.\n"
    elif field == "summary":
        extra = "- Keep it as one or two paragraphs of continuous text.\n"
        length_hint = "- Length target: roughly 150–250 words.\n"
    elif field == "title":
        extra = "- Return a single-line title only, without quotes or extra commentary.\n"
        length_hint = "- Keep it concise and natural in the target language.\n"
    else:  # subtitle or other short fields
        extra = "- Keep formatting minimal; plain text is fine.\n"
        length_hint = "- Preserve meaning and nuance; do not add explanations.\n"

    prompt = (
        f"Translate the following {field} from English to {target_lang}.\n"
        "- The text comes from a climate change adaptation case study.\n"
        f"{extra}"
        f"{length_hint}"
        "- Do NOT add any explanations, notes, or metadata; return ONLY the translated text.\n\n"
        f"Original {field}:\n"
        f"{src}"
    )

    try:
        print(f"Translating field '{field}' to {target_lang}...")
        response = genai_client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(max_output_tokens=1200),
        )

        result_text: str | None = None
        if hasattr(response, "text") and response.text:
            result_text = response.text
        elif hasattr(response, "candidates") and response.candidates:
            candidate = response.candidates[0]
            if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
                if isinstance(candidate.content.parts, list):
                    result_text = "".join(
                        [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                    )
                else:
                    result_text = str(candidate.content.parts)
            elif hasattr(candidate.content, "text"):
                result_text = candidate.content.text

        translated = (result_text or "").strip()
        global_translation_cache[cache_key] = translated
        _save_json_cache(TRANSLATION_CACHE_FILE, global_translation_cache)
        return translated
    except Exception as e:  # noqa: BLE001
        print(f"Error translating field '{field}' to {target_lang}: {e}", file=sys.stderr)
        global_translation_cache[cache_key] = ""
        _save_json_cache(TRANSLATION_CACHE_FILE, global_translation_cache)
        return ""


def translate_record(data: dict, target_lang: str) -> dict:
    """
    Build a translation-only record for UI:
    - source_file
    - lang
    - title, subtitle, summary, fulltext (translated)
    """
    source_file = data.get("source_file", "")

    result: dict = {
        "source_file": source_file,
        "lang": target_lang,
    }

    for field in ("title", "subtitle", "summary", "fulltext"):
        original = data.get(field, "")
        translated = _translate_text(original, target_lang, field)
        result[field] = translated

    return result


def process_file(path: Path, output_dir: Path, target_lang: str) -> None:
    """
    Read one augmented JSON, produce a translations-only JSON in the same folder.
    """
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:  # noqa: BLE001
        print(f"Error reading {path}: {e}", file=sys.stderr)
        return

    if not isinstance(raw, dict):
        print(f"Skipping {path.name}: expected a single JSON object.", file=sys.stderr)
        return

    print(f"\nTranslating {path.name} to {target_lang}...")
    translated_record = translate_record(raw, target_lang)

    out_name = f"{path.stem}_{target_lang}.json"
    out_path = output_dir / out_name
    out_path.write_text(json.dumps(translated_record, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote translation file: {out_path.relative_to(REPO_ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Translate user-visible fields from augmented case-study JSON files into another language."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help="Directory containing augmented JSON files (default: pipeline/augmented).",
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="*_en_augmented.json",
        help="Glob pattern to select input JSON files (default: *_en_augmented.json).",
    )
    parser.add_argument(
        "--lang",
        type=str,
        default="es",
        help="Target language code (default: es).",
    )
    args = parser.parse_args()

    if not args.input.exists():
        print(f"Input directory does not exist: {args.input}", file=sys.stderr)
        return 1

    files = sorted(args.input.glob(args.pattern))
    if not files:
        print(f"No JSON files matched {args.pattern} in {args.input}", file=sys.stderr)
        return 1

    print(f"Found {len(files)} JSON files to translate in {args.input}")
    for path in files:
        process_file(path, args.input, args.lang)

    print("Translation complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

