#!/usr/bin/env python3
"""
Translate user-visible fields from augmented case-study JSON files into another language.

Input:  JSON files from pipeline/augmented (one object per file), generated by augment_with_ai.py.
Output: For each input file, a translation-only JSON:
        page_0_en_augmented.json -> page_0_en_augmented_es.json

CLI: python translate_augmented.py [--input pipeline/augmented] [--pattern '*_en_augmented.json'] [--lang es]

Translated fields:
- fulltext, title, summary, subtitle
- recipe.ingredients (canonical keys), when English augmented JSON has a renderable recipe

Each translation JSON contains:
- source_file: original HTML file path (foreign key)
- lang: target language code (e.g. "es")
- title, subtitle, summary, fulltext: translated strings
- recipe: { lang, ingredients } when recipe translation applies
"""

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from google.genai import types


REPO_ROOT = Path(__file__).resolve().parent.parent
PIPELINE_DIR = REPO_ROOT / "pipeline"
DEFAULT_INPUT_DIR = PIPELINE_DIR / "augmented"

# Load env from repo and pipeline
load_dotenv(REPO_ROOT / ".env")
load_dotenv(PIPELINE_DIR / ".env")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not set. Please define it in .env.", file=sys.stderr)
    sys.exit(1)

# Normalise model ID for google-genai (strip provider prefix like 'gemini/')
_raw_model = os.getenv("GEMINI_MODEL_TRANSLATE", "gemini-2.5-flash")
GEMINI_MODEL = _raw_model.split("/")[-1]

genai_client = genai.Client(api_key=GEMINI_API_KEY)

# Translation cache
CACHE_DIR = PIPELINE_DIR / "caches"
CACHE_DIR.mkdir(parents=True, exist_ok=True)
TRANSLATION_CACHE_FILE = CACHE_DIR / "translation_cache.json"
RECIPE_TRANSLATION_CACHE_FILE = CACHE_DIR / "recipe_translation_cache.json"
RECIPE_TRANSLATION_CACHE_VERSION = "v2"
TRANSLATION_CACHE_VERSION = "v3"
FULLTEXT_CHUNK_CHAR_BUDGET = 4000
FULLTEXT_SINGLE_CALL_THRESHOLD = 4000
MAX_TRANSLATION_OUTPUT_TOKENS = 8192
LENGTH_PARITY_FLOOR = 0.5
PARITY_REPORT_FILE = CACHE_DIR / "translation_parity_report.json"

HEADING_RE = re.compile(r"^#{1,6}\s")
FENCE_RE = re.compile(r"^```")

# ISO 639-1 → English name for prompts. Bare codes like "it" confuse LLMs (ambiguous vs. English "it").
TARGET_LANGUAGE_LABELS: dict[str, str] = {
    "en": "English",
    "es": "Spanish",
    "it": "Italian",
    "fr": "French",
    "de": "German",
    "pt": "Portuguese",
    "nl": "Dutch",
    "pl": "Polish",
}


def _target_language_label(code: str) -> str:
    c = (code or "").strip().lower()
    return TARGET_LANGUAGE_LABELS.get(c, f"the language with ISO 639-1 code {c!r}")


# Canonical keys (must match augment_with_ai.RECIPE_CANONICAL_KEYS / knowledge.recipe).
RECIPE_CANONICAL_KEYS: tuple[str, ...] = (
    "who_is_involved",
    "economic_data",
    "context_summary",
    "challenges",
    "policy_context",
    "legal_aspects",
    "objectives",
    "solutions_implemented",
    "implementation_phases",
    "success_and_limiting",
    "benefits",
    "lessons_learnt",
    "transferability",
)


def _load_json_cache(path: Path) -> dict:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception as e:  # noqa: BLE001
            print(f"Error loading cache {path.name}: {e}", file=sys.stderr)
            return {}
    return {}


def _save_json_cache(path: Path, cache: dict) -> None:
    try:
        path.write_text(json.dumps(cache, indent=2, ensure_ascii=False), encoding="utf-8")
    except Exception as e:  # noqa: BLE001
        print(f"Error saving cache {path.name}: {e}", file=sys.stderr)


global_translation_cache = _load_json_cache(TRANSLATION_CACHE_FILE)
global_recipe_translation_cache = _load_json_cache(RECIPE_TRANSLATION_CACHE_FILE)
parity_report: dict[str, dict[str, dict]] = {}


def _text_fingerprint(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _translation_generate_config() -> types.GenerateContentConfig:
    return types.GenerateContentConfig(
        max_output_tokens=MAX_TRANSLATION_OUTPUT_TOKENS,
        temperature=0,
        thinking_config=types.ThinkingConfig(thinking_budget=0),
    )


def _split_markdown_sections(text: str) -> list[str]:
    """Split at markdown headings when outside fenced code blocks."""
    if not text:
        return []
    lines = text.splitlines(keepends=True)
    if not lines:
        return [text] if text.strip() else []

    sections: list[str] = []
    buf: list[str] = []
    in_fence = False

    def flush() -> None:
        if buf:
            chunk = "".join(buf)
            if chunk.strip():
                sections.append(chunk)
            buf.clear()

    for line in lines:
        stripped = line.strip()
        if FENCE_RE.match(stripped):
            in_fence = not in_fence
            buf.append(line)
            continue
        if not in_fence and HEADING_RE.match(stripped) and buf:
            flush()
        buf.append(line)

    flush()
    return sections if sections else [text]


def _split_on_blank_lines(text: str, max_chars: int) -> list[str]:
    """Split oversized prose on blank-line boundaries (never inside fences)."""
    parts: list[str] = []
    buf: list[str] = []
    in_fence = False

    def flush() -> None:
        if buf:
            chunk = "".join(buf)
            if chunk.strip():
                parts.append(chunk)
            buf.clear()

    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if FENCE_RE.match(stripped):
            in_fence = not in_fence
            buf.append(line)
            continue
        if not in_fence and stripped == "" and buf:
            flush()
            buf.append(line)
            continue
        buf.append(line)

    flush()
    if not parts:
        return [text]

    packed: list[str] = []
    current = ""
    for part in parts:
        if len(part) > max_chars:
            if current:
                packed.append(current)
                current = ""
            for i in range(0, len(part), max_chars):
                packed.append(part[i : i + max_chars])
            continue
        if current and len(current) + len(part) > max_chars:
            packed.append(current)
            current = part
        else:
            current = current + part if current else part
    if current:
        packed.append(current)
    return packed


def _pack_sections_into_chunks(sections: list[str], max_chars: int) -> list[str]:
    chunks: list[str] = []
    current = ""
    for section in sections:
        units = [section] if len(section) <= max_chars else _split_on_blank_lines(section, max_chars)
        for unit in units:
            if len(unit) > max_chars:
                if current:
                    chunks.append(current)
                    current = ""
                for i in range(0, len(unit), max_chars):
                    chunks.append(unit[i : i + max_chars])
                continue
            if current and len(current) + len(unit) > max_chars:
                chunks.append(current)
                current = unit
            else:
                current = current + unit if current else unit
    if current:
        chunks.append(current)
    return chunks if chunks else sections


def _chunk_fulltext(text: str) -> list[str]:
    src = text.strip()
    if not src:
        return []
    if len(src) <= FULLTEXT_SINGLE_CALL_THRESHOLD:
        return [src]
    sections = _split_markdown_sections(src)
    return _pack_sections_into_chunks(sections, FULLTEXT_CHUNK_CHAR_BUDGET)


def _field_prompt_instructions(field: str) -> tuple[str, str]:
    if field == "fulltext":
        extra = (
            "- Preserve the markdown structure (headings, bullet lists, code blocks) as much as possible.\n"
            "- Preserve links and URLs; translate only the descriptive text.\n"
        )
        length_hint = "- Keep roughly the same length and level of detail as the original.\n"
    elif field == "summary":
        extra = "- Keep it as one or two paragraphs of continuous text.\n"
        length_hint = "- Length target: roughly 150–250 words.\n"
    elif field == "title":
        extra = "- Return a single-line title only, without quotes or extra commentary.\n"
        length_hint = "- Keep it concise and natural in the target language.\n"
    else:
        extra = "- Keep formatting minimal; plain text is fine.\n"
        length_hint = "- Preserve meaning and nuance; do not add explanations.\n"
    return extra, length_hint


def _extract_response_text(response) -> str:  # noqa: ANN001
    result_text: str | None = None
    if hasattr(response, "text") and response.text:
        result_text = response.text
    elif hasattr(response, "candidates") and response.candidates:
        candidate = response.candidates[0]
        if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
            if isinstance(candidate.content.parts, list):
                result_text = "".join(
                    [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                )
            else:
                result_text = str(candidate.content.parts)
        elif hasattr(candidate.content, "text"):
            result_text = candidate.content.text
    return (result_text or "").strip()


def _call_gemini_translate(src: str, target_lang: str, field: str) -> str:
    extra, length_hint = _field_prompt_instructions(field)
    lang_label = _target_language_label(target_lang)
    prompt = (
        f"Translate the following {field} from English into {lang_label} (ISO 639-1 language code: {target_lang}).\n"
        "- The text comes from a climate change adaptation case study.\n"
        f"{extra}"
        f"{length_hint}"
        "- Do NOT add any explanations, notes, or metadata; return ONLY the translated text.\n\n"
        f"Original {field}:\n"
        f"{src}"
    )
    response = genai_client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
        config=_translation_generate_config(),
    )
    return _extract_response_text(response)


def _record_length_parity(source_file: str, target_lang: str, source_len: int, translated_len: int) -> None:
    ratio = translated_len / source_len if source_len else 0.0
    below_floor = ratio < LENGTH_PARITY_FLOOR
    entry = {
        "source_len": source_len,
        "translated_len": translated_len,
        "ratio": round(ratio, 4),
        "below_floor": below_floor,
    }
    parity_report.setdefault(source_file, {})[target_lang] = entry
    if below_floor:
        print(
            f"WARNING: fulltext length parity below floor ({ratio:.2f} < {LENGTH_PARITY_FLOOR}) "
            f"for {source_file} [{target_lang}]",
            file=sys.stderr,
        )


def _save_parity_report() -> None:
    if not parity_report:
        return
    try:
        PARITY_REPORT_FILE.write_text(json.dumps(parity_report, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"Wrote parity report: {PARITY_REPORT_FILE.relative_to(REPO_ROOT)}")
    except Exception as e:  # noqa: BLE001
        print(f"Error saving parity report: {e}", file=sys.stderr)



def _coerce_recipe_value(val) -> str:  # noqa: ANN001
    if val is None:
        return ""
    if isinstance(val, str):
        return val
    if isinstance(val, (dict, list)):
        return json.dumps(val, ensure_ascii=False)
    return str(val)


def _normalize_english_recipe_ingredients(raw: dict) -> dict[str, str]:
    out = {k: "" for k in RECIPE_CANONICAL_KEYS}
    if not isinstance(raw, dict):
        return out
    for k in RECIPE_CANONICAL_KEYS:
        out[k] = _coerce_recipe_value(raw.get(k))
    return out


def _recipe_ingredients_has_content(ingredients: dict[str, str]) -> bool:
    return any(isinstance(v, str) and v.strip() for v in ingredients.values())


def _recipe_ingredients_fingerprint(ingredients: dict[str, str]) -> str:
    payload = json.dumps({k: ingredients.get(k, "") for k in RECIPE_CANONICAL_KEYS}, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _recipe_ingredients_json_schema() -> types.Schema:
    props: dict[str, types.Schema] = {}
    for key in RECIPE_CANONICAL_KEYS:
        label = " ".join(key.split("_"))
        props[key] = types.Schema(
            type=types.Type.STRING,
            description=f"Markdown for {label} translated to the target language, or empty if the English value was empty.",
        )
    return types.Schema(
        type=types.Type.OBJECT,
        properties=props,
    )


def _parse_json_object_from_gemini(response) -> dict | None:  # noqa: ANN001
    if response is None:
        return None
    parsed = getattr(response, "parsed", None)
    if parsed is not None:
        if isinstance(parsed, dict):
            return parsed
        if hasattr(parsed, "model_dump") and callable(parsed.model_dump):
            dumped = parsed.model_dump()
            return dumped if isinstance(dumped, dict) else None
    result_text: str | None = None
    if hasattr(response, "text") and response.text:
        result_text = response.text
    elif hasattr(response, "candidates") and response.candidates:
        candidate = response.candidates[0]
        if hasattr(candidate, "content") and hasattr(candidate.content, "parts") and candidate.content.parts:
            if isinstance(candidate.content.parts, list):
                result_text = "".join(
                    [p.get("text", "") if isinstance(p, dict) else str(p) for p in candidate.content.parts]
                )
            else:
                result_text = str(candidate.content.parts)
        elif hasattr(candidate.content, "text"):
            result_text = candidate.content.text
    if not result_text or not str(result_text).strip():
        return None
    cleaned = (
        str(result_text)
        .strip()
        .replace("```json", "")
        .replace("```", "")
        .strip()
    )
    if not cleaned:
        return None
    try:
        out = json.loads(cleaned)
    except json.JSONDecodeError:
        return None
    return out if isinstance(out, dict) else None


def _finalize_translated_recipe_ingredients(parsed: dict) -> dict[str, str]:
    out = {k: "" for k in RECIPE_CANONICAL_KEYS}
    for k in RECIPE_CANONICAL_KEYS:
        if k in parsed:
            out[k] = _coerce_recipe_value(parsed[k])
    return out


def _translate_recipe_ingredients_structured(en: dict[str, str], target_lang: str) -> dict[str, str] | None:
    en_json = json.dumps({k: en.get(k, "") for k in RECIPE_CANONICAL_KEYS}, ensure_ascii=False, indent=2)
    lang_label = _target_language_label(target_lang)
    prompt = (
        f"You translate climate adaptation case study 'recipe' sections (markdown strings per field).\n"
        f"Target language: {lang_label} (ISO 639-1: {target_lang}).\n"
        f"- Translate each non-empty English value into natural {lang_label}.\n"
        "- Preserve markdown structure (headings, lists, bold) as much as possible.\n"
        "- If the English value for a key is empty or whitespace-only, the output for that key MUST be an empty string.\n"
        "- Do not add or remove keys. Do not add title, short_description, or sdgs.\n"
        "- Return only valid JSON matching the schema (no commentary).\n\n"
        "English ingredients JSON:\n"
        f"{en_json}"
    )
    response = genai_client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            max_output_tokens=8192,
            temperature=0,
            response_mime_type="application/json",
            response_schema=_recipe_ingredients_json_schema(),
        ),
    )
    parsed = _parse_json_object_from_gemini(response)
    if not parsed:
        return None
    return _finalize_translated_recipe_ingredients(parsed)


def _translate_recipe_ingredients_per_key(en: dict[str, str], target_lang: str) -> dict[str, str]:
    """Fallback: reuse field translator (proven JSON path) per non-empty section."""
    out = {k: "" for k in RECIPE_CANONICAL_KEYS}
    for k in RECIPE_CANONICAL_KEYS:
        src = (en.get(k) or "").strip()
        if not src:
            continue
        out[k] = _translate_text(src, target_lang, f"recipe_{k}")
    return out


def _translate_recipe_ingredients(en_ingredients: dict[str, str], target_lang: str) -> dict[str, str]:
    """
    Translate all recipe section strings to target_lang; cached on disk (structured output fingerprint).
    Falls back to per-section translation if structured JSON is not returned.
    """
    global global_recipe_translation_cache
    en = dict(en_ingredients)
    if not _recipe_ingredients_has_content(en):
        return {k: "" for k in RECIPE_CANONICAL_KEYS}

    fp = _recipe_ingredients_fingerprint(en)
    cache_key = f"{RECIPE_TRANSLATION_CACHE_VERSION}:{target_lang}:{fp}"
    if cache_key in global_recipe_translation_cache:
        cached = global_recipe_translation_cache[cache_key]
        if isinstance(cached, dict):
            return _finalize_translated_recipe_ingredients(cached)

    try:
        print(f"Translating recipe ingredients to {target_lang}...")
        out = _translate_recipe_ingredients_structured(en, target_lang)
        if out is None:
            out = _translate_recipe_ingredients_structured(en, target_lang)
        if out is None or not _recipe_ingredients_has_content(out):
            print(
                "Recipe structured translation failed or empty; falling back to per-section translation.",
                file=sys.stderr,
            )
            out = _translate_recipe_ingredients_per_key(en, target_lang)
        if _recipe_ingredients_has_content(out):
            global_recipe_translation_cache[cache_key] = out
            _save_json_cache(RECIPE_TRANSLATION_CACHE_FILE, global_recipe_translation_cache)
        return out
    except Exception as e:  # noqa: BLE001
        print(f"Error translating recipe to {target_lang}: {e}", file=sys.stderr)
        return {k: "" for k in RECIPE_CANONICAL_KEYS}


def _translate_text(text: str, target_lang: str, field: str) -> str:
    """
    Translate a single text field to target_lang, with caching.

    field is one of: fulltext, title, summary, subtitle, or recipe_* keys.
    For fulltext, use _translate_fulltext instead.
    """
    global global_translation_cache
    if not text:
        return ""

    src = text.strip()
    cache_key = f"{TRANSLATION_CACHE_VERSION}:{target_lang}:{field}:{src}"
    if cache_key in global_translation_cache:
        cached = global_translation_cache[cache_key]
        if isinstance(cached, str) and cached:
            return cached

    try:
        print(f"Translating field '{field}' to {target_lang}...")
        translated = _call_gemini_translate(src, target_lang, field)
        if translated:
            global_translation_cache[cache_key] = translated
            _save_json_cache(TRANSLATION_CACHE_FILE, global_translation_cache)
        return translated
    except Exception as e:  # noqa: BLE001
        print(f"Error translating field '{field}' to {target_lang}: {e}", file=sys.stderr)
        return ""


def _translate_fulltext(text: str, target_lang: str, source_file: str = "") -> str:
    """Translate fulltext with section-aware chunking and length-parity validation."""
    global global_translation_cache
    src = text.strip()
    if not src:
        return ""

    chunks = _chunk_fulltext(src)
    translated_parts: list[str] = []

    for i, chunk in enumerate(chunks):
        chunk_field = "fulltext" if len(chunks) == 1 else f"fulltext_chunk_{i}"
        cache_key = f"{TRANSLATION_CACHE_VERSION}:{target_lang}:fulltext:{_text_fingerprint(chunk)}"
        if cache_key in global_translation_cache:
            cached = global_translation_cache[cache_key]
            if isinstance(cached, str) and cached:
                translated_parts.append(cached)
                continue

        try:
            label = f"fulltext chunk {i + 1}/{len(chunks)}" if len(chunks) > 1 else "fulltext"
            print(f"Translating {label} to {target_lang}...")
            translated = _call_gemini_translate(chunk, target_lang, "fulltext")
            if not translated:
                print(f"Error: empty translation for {label} [{target_lang}]", file=sys.stderr)
                return ""
            global_translation_cache[cache_key] = translated
            _save_json_cache(TRANSLATION_CACHE_FILE, global_translation_cache)
            translated_parts.append(translated)
        except Exception as e:  # noqa: BLE001
            print(f"Error translating fulltext chunk to {target_lang}: {e}", file=sys.stderr)
            return ""

    result = "".join(translated_parts)
    _record_length_parity(source_file, target_lang, len(src), len(result))
    return result


def translate_record(data: dict, target_lang: str) -> dict:
    """
    Build a translation-only record for UI:
    - source_file
    - lang
    - title, subtitle, summary, fulltext (translated)
    - recipe (translated ingredients) when English recipe has renderable content
    """
    source_file = data.get("source_file", "")

    result: dict = {
        "source_file": source_file,
        "lang": target_lang,
    }

    for field in ("title", "subtitle", "summary"):
        original = data.get(field, "")
        translated = _translate_text(original, target_lang, field)
        result[field] = translated

    original_fulltext = data.get("fulltext", "")
    result["fulltext"] = _translate_fulltext(original_fulltext, target_lang, source_file)

    recipe = data.get("recipe")
    if isinstance(recipe, dict):
        raw_ing = recipe.get("ingredients")
        if isinstance(raw_ing, dict):
            en_ing = _normalize_english_recipe_ingredients(raw_ing)
            if _recipe_ingredients_has_content(en_ing):
                translated_ing = _translate_recipe_ingredients(en_ing, target_lang)
                if _recipe_ingredients_has_content(translated_ing):
                    result["recipe"] = {"lang": target_lang, "ingredients": translated_ing}

    return result


def process_file(path: Path, output_dir: Path, target_lang: str) -> None:
    """
    Read one augmented JSON, produce a translations-only JSON in the same folder.
    """
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:  # noqa: BLE001
        print(f"Error reading {path}: {e}", file=sys.stderr)
        return

    if not isinstance(raw, dict):
        print(f"Skipping {path.name}: expected a single JSON object.", file=sys.stderr)
        return

    print(f"\nTranslating {path.name} to {target_lang}...")
    translated_record = translate_record(raw, target_lang)

    out_name = f"{path.stem}_{target_lang}.json"
    out_path = output_dir / out_name
    out_path.write_text(json.dumps(translated_record, indent=2, ensure_ascii=False), encoding="utf-8")
    try:
        rel = out_path.resolve().relative_to(REPO_ROOT.resolve())
        print(f"Wrote translation file: {rel}")
    except ValueError:
        print(f"Wrote translation file: {out_path}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Translate augmented case-study JSON (title, subtitle, summary, fulltext, recipe) "
            "via Gemini; caches under pipeline/caches/."
        ),
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help="Directory containing augmented JSON files (default: pipeline/augmented).",
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="*_en_augmented.json",
        help="Glob pattern to select input JSON files (default: *_en_augmented.json).",
    )
    parser.add_argument(
        "--lang",
        type=str,
        default="es",
        help="Target language code (default: es).",
    )
    args = parser.parse_args()

    if not args.input.exists():
        print(f"Input directory does not exist: {args.input}", file=sys.stderr)
        return 1

    files = sorted(args.input.glob(args.pattern))
    if not files:
        print(f"No JSON files matched {args.pattern} in {args.input}", file=sys.stderr)
        return 1

    print(f"Found {len(files)} JSON files to translate in {args.input}")
    for path in files:
        process_file(path, args.input, args.lang)

    _save_parity_report()
    print("Translation complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

