do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
      and t.typname = 'app_role'
  ) then
    create type public.app_role as enum ('connected_admin');
  end if;
end
$$;

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  role public.app_role not null,
  granted_at timestamptz not null default now(),
  granted_by uuid references auth.users (id) on delete set null,
  unique (user_id, role)
);

comment on table public.user_roles is 'Explicit elevated application role assignments for authenticated users.';
comment on column public.user_roles.user_id is 'Supabase auth user receiving the elevated application role.';
comment on column public.user_roles.role is 'Application role granted to the user. Normal authenticated users have no row.';
comment on column public.user_roles.granted_at is 'When the elevated role was granted or last refreshed.';
comment on column public.user_roles.granted_by is 'Optional auth user that granted the elevated role.';

create index if not exists user_roles_user_id_idx on public.user_roles (user_id);

alter table public.user_roles enable row level security;

drop policy if exists "Allow auth admin to read user roles" on public.user_roles;
create policy "Allow auth admin to read user roles"
on public.user_roles
as permissive
for select
to supabase_auth_admin
using (true);

grant usage on schema public to supabase_auth_admin;
grant usage on type public.app_role to supabase_auth_admin;
grant select on table public.user_roles to supabase_auth_admin;
revoke all on table public.user_roles from authenticated, anon, public;
